name: SCP Test Deploy

on:
    push:
        branches:
            - working

jobs:
    pandoc:
        runs-on: ubuntu-latest
        name: Pandoc
        container:
            image: docker://pandoc/core:2.9
            options: --entrypoint=sh
        steps:
        - name: Check out code
          uses: actions/checkout@v4
        - name: Markdown to Html
          run: |
            find ./amanasie_simple/ -name '*.md' -type f -exec sh -c 'pandoc -f markdown -t html -o ${0%.md}.html ${0}' {} \;
    build:
        runs-on: ubuntu-latest
        name: Build
        needs: pandoc
        steps:
        - name: Check out code
          uses: actions/checkout@v4
        - name: SCP Deploy
          uses: appleboy/scp-action@v0.1.7
          with:
            key: ${{ secrets.SK }}
            port: ${{ secrets.SSH_PORT }}
            username: ${{ secrets.SSH_USERNAME }}
            host: ${{ secrets.SSH_HOST }}
            source: 'amanasie_simple/*'
            target: '~/www/test'
